--- 
- 
  hosts: localhost
  tasks: 
    - 
      add_host: 
        group: workstation
        name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
      name: "Create workstation inventory"
- 
  become: true
  hosts: workstation
  roles: 
    - osp-servers
